### PR TITLE
udpates to versions and gitignore

### PR DESCRIPTION
**Pull request by jkeenest**
made some changes to reference the latest versions of scaleIO and centos

### CODE REVIEW

**Comment by jonasrosland** [comment]
Looks good to me. @clintonskitson?

**Comment by clintonskitson** [comment]
Thanks for the PR! Can I ask that you add a commit that updates the example files as well to include the version change?

**Comment by jkeenest** [comment]
Certainly.  On it...

**Comment by clintonskitson** [comment]
Triple bonus if you can include the updated $rpm_suffix variable as seen in Arrowhead.

https://github.com/emccode/arrowhead/blob/master/vagrantspice/VagrantSpicedir/aws/sync/puppet/manifests/site.pp

This will allow for CentOS7.

**Comment by jkeenest** [comment]
Just updated with all files. I'll have to work on the $rpm_suffix later

**Pull request merged**
